version: "3"

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file: app.env
    depends_on:
      - db

  db:
    image: mdillon/postgis:11-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: app.env

volumes:
  db-data:
